### ISSUE TITLE
Home: Banner features

### ISSUE THREAD

**Issue by ccamara** [ccamara/precocalsa-hugo#13]
Tarea Hija de #10 

![Screenshot_2021-01-06 Precocalsa](https://user-images.githubusercontent.com/706549/103799127-930b7f80-5042-11eb-99c3-d2b515aa0704.png)

Por defecto, la portada puede mostrar "Banner features": hasta 4 elementos destacados con una imagen y un texto bajo el slideshow.

Habría que decir si lo mostramos o no. En caso afirmativo, necesitaría la siguiente información:

- [ ] Título
- [ ] Icono de esta lista: https://fontawesome.com/v4.7.0/icons/ 
- [ ] Texto breve

**Comment by ccamara** [comment]
@cjavigb Si decides mostrarlo, necesitaría la información de hasta 4 características de precocalsa que quieras destacar.

**Comment by cjavigb** [comment]
No se me ocurre que podríamos destacar aquí. El servicio que ofrecemos se reduce al producto en si.

**Comment by ccamara** [comment]
OK! Banner oculto. Gracias!
