### ISSUE TITLE
Home: recomendaciones de clientes

### ISSUE THREAD

**Issue by ccamara** [ccamara/precocalsa-hugo#16]
En la home (#10) existe la opción de mostrar recomendaciones de clientes (testimonials)

![Screenshot_2021-01-06 Precocalsa](https://user-images.githubusercontent.com/706549/103809053-d836ae00-5050-11eb-8c5f-c65035e0620b.png)

@cjavigb, **Hay que decidir si queremos mostrarlo o no**. En caso afirmativo, tendrías que pedirle a algún(os) cliente(s) de confianza que os escriban alguna recomendación (no sé si se pueden recomendar empresas en linkedin como se hace con las personas, en ese caso podrías pedirlo allí y copiarlo luego en la web). Para la web necesitaríamos:

- [ ] Foto del cliente (de su cara o el logo de su empresa, quizá?)
- [ ] Nombre del cliente
- [ ] Profesión
- [ ] Texto de la recomendación

**Comment by cjavigb** [comment]
De momento esto lo apagamos.
Veo de recopilar información de clientes y lo abriríamos.

**Comment by ccamara** [comment]
Hecho!
