### ISSUE TITLE
Página de equipo

### ISSUE THREAD

**Issue by ccamara** [ccamara/precocalsa-hugo#17]
La plantilla permite tener una página de "equipo" como esta:

![Screenshot_2021-01-06 Team](https://user-images.githubusercontent.com/706549/103812555-927ce400-5056-11eb-9427-0c44b2937dd9.jpg)

@cjavigb , Hay que decidir si queréis mostrarla o no. En caso afirmativo necesitaría los datos de cada una de las personas que queréis que salgan:

- [ ] Nombre
- [ ] Foto (todas del mismo tamaño, proporción vertical)
- [ ] Cargo
- [ ] Redes sociales (opcional)

**Comment by cjavigb** [comment]
De momento apagada.

**Comment by ccamara** [comment]
OK! Hecho!
